[phases.setup]
nixPkgs = [
    "nodejs_23",
    "pnpm",
]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
dependsOn = ['install']
cmds = ['pnpm run build']
cacheDirectories = ['node_modules/.cache']

[start]
cmd = 'pnpm run start'
