name: Announcements
about: Official announcements from the ResuGen team. (Maintainer use only)
title: '[ANNOUNCEMENT] <Brief Title>'
labels: ['announcement']
body:
  - type: markdown
    attributes:
      value: |
        This category is for official announcements from the ResuGen team, such as new releases, important updates, or major news.
        **This template is for maintainer use only.**

  - type: textarea
    id: announcement-content
    attributes:
      label: Announcement Content
      description: Please provide the full details of the announcement.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Relevant Links (Optional)
      description: Add any links to release notes, documentation, or other resources.
    validations:
      required: false
